### ISSUE TITLE
Remove dependencies from dist/responsive.js

### ISSUE THREAD

**Issue by shuhei** [axyz/rezponsive#3]
Currently `dist/responsive.js` includes `prop-types` and its dependencies, which could be deduped if this library's user is also using `prop-types`.

![screen shot 2018-01-30 at 17 06 22](https://user-images.githubusercontent.com/498635/35576702-f336fb56-05df-11e8-8769-3c67142581a9.png)

If we remove `prop-types` and its dependencies from the dist file, we can potentially remove about 9KB gzipped.

**Comment by shuhei** [comment]
@axyz If you are fine with this, I can make a PR.

**Comment by shuhei** [comment]
Also, if you stop supporting non-common.js usage, we can just transpile the source code with Babel and remove more code generated by webpack.

**Comment by shuhei** [comment]
Of course the duplication is also reduced by gzipping, but I found my app bundle size decreased by 3.3KB by the improvement of #4.

**Comment by axyz** [comment]
@shuhei yeah sure can use env variable to include them in dev, but not in dist
